# NumPy Functions

In [1]:
#we have imported numpy as np
import numpy as np

# arange()

In [2]:
#we can arrange the series (default is asecending order)by
#np.arange(start, end, step)
ar1_1d = np.arange(1,21)
print(ar1_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
#smartly using steps to create even array
ar_even = np.arange(2,21,2)
print(ar_even)
#try yourself for odd array

[ 2  4  6  8 10 12 14 16 18 20]


# linspace()

In [4]:
#this creates sequences of evenly spaced numbers
ar2 = np.linspace(1,5,4) #divided in four parts and evenly spaced
print(ar2)

[1.         2.33333333 3.66666667 5.        ]


# reshape()

In [5]:
#use to reshape 1d to 2d to 3d or vice versa
ar3_2d = ar1_1d.reshape(2,6)
print(ar3_2d)

ValueError: cannot reshape array of size 20 into shape (2,6)

In [6]:
#we have to give valid row and column as 20 numbers can't come in 2,6
ar4_2d = ar1_1d.reshape(2,10)
print(ar4_2d)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [7]:
#1d to 3rd (three values are required i.e. 3d, 2d, 1d in order)
#i.e.        .reshape(3d,2d,1d)
ar5_3d = ar1_1d.reshape(2,5,2) #this is 2, 3d array each composed of 5, 2d array made by 1d array of 2 
print(ar5_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [8]:
#now we'll use composition of functions
ar5_2d = np.arange(1,13).reshape(2,6)
print(ar5_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [9]:
#this converts multi-dimension array into 1d array
ar6_1d = ar5_2d.ravel()
print(ar6_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# flatten()

In [10]:
#this also converts multi-dimension array into 1d array
ar7_1d = ar5_2d.flatten()
print(ar7_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
#we can use any to convert to 1d array
#the key difference is: flatten is a method of an ndarray object and hence can only be called for true numpy arrays. ravel is a library-level function and hence can be called on any object that can successfully be parsed.
#if you didn't understood this don't worry just remember the above and will understand this in advance applications.



#if u can't go forward without eating this, then try below:

# import numpy
# a = numpy.array([[1,2],[3,4]])

# r = numpy.ravel(a)
# f = numpy.ndarray.flatten(a)  

# print(id(a))
# print(id(r))
# print(id(f))

# print(r)
# print(f)

# print("\nbase r:", r.base)
# print("\nbase f:", f.base)

# ---returns---
# 140541099429760
# 140541099471056
# 140541099473216

# [1 2 3 4]
# [1 2 3 4]

# base r: [[1 2]
#  [3 4]]

# base f: None
# In the upper example:

# the memory locations of the results are different,
# the results look the same
# flatten would return a copy
# ravel would return a view.
# How we check if something is a copy? Using the .base attribute of the ndarray. If it's a view, the base will be the original array; if it is a copy, the base will be None.

# transpose()

In [12]:
#give the transpose of matrix i.e. row to column and column to rows
ar8_2d = ar5_2d.transpose() #(2,6) to (6,2) (parenthesis)
print(ar8_2d)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [13]:
#we can also use sort from of tranpose i.e. T
ar8_2d = ar5_2d.T #(2,6) to (6,2) (no parenthesis)
print(ar8_2d)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
