In [13]:
#imported numpy as np
import numpy as np

In [14]:
#created 1d array
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [15]:
#we wanted to know the type
type(arr_1d)

numpy.ndarray

In [16]:
#we wanted to know the dimension
arr_1d.ndim

1

In [17]:
#we created to 2d array
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
#we wanted to know the dimension
arr_2d.ndim

2

In [19]:
#we wanted to know the size i.e. total number of elements
arr_1d.size

5

In [20]:
#we wanted to know the size i.e. total number of elements
arr_2d.size

8

In [21]:
#we wanted to know the shape of array which is given out as tuple
arr_1d.shape

(5,)

In [22]:
#we wanted to know the shape of array i.e. given in rows & columns
arr_2d.shape

(2, 4)

In [23]:
#we want to know the data type
arr_1d.dtype

dtype('int64')

In [24]:
#int64 means data type is integer represented in 64 bit format.
arr_2d.dtype

dtype('int64')