# Concatination

In [1]:
import numpy as np

In [2]:
ar1 = np.arange(1,17).reshape(4,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
ar2 = np.arange(17,33).reshape(4,4)
print(ar2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [4]:
#created two list
lst1 = [1,2,3,4]
lst2 = [9,8,7,6]

In [5]:
#concatenate list 1 & list 2 but this method will add matrix
lst1 + lst2

[1, 2, 3, 4, 9, 8, 7, 6]

In [6]:
#concatenation of array (column wise) (method 1)
np.concatenate((ar1,ar2))   #default axis = 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [7]:
#concatenation of array (row wise)  (method 1)
np.concatenate((ar1,ar2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [8]:
#concatenation of array (column wise) (method 2)
np.vstack((ar1,ar2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [9]:
#concatenation of array (row wise) (method 2)
np.hstack((ar1,ar2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [10]:
#we can concatenate multiple array by giving input with ',' in between
#concatenation of array (row wise) (method 2)
np.hstack((ar1,ar2,ar1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# Splitting

In [11]:
#splitting of array (default is row wise, i.e. axis = 0)
spl = np.split(ar1,2) #split ar1 in 2 array
print(spl)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [12]:
#split will split array in form of list
type(spl)

list

In [13]:
#calling 1st item of list
spl[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
#1st item of list is array
type(spl[0])

numpy.ndarray

In [15]:
#From above if can be infered that 'split' splits the array and store it in a list format.

In [16]:
#splitting of array (default is column wise, i.e. axis = 1)
spl = np.split(ar1,2,axis=1) #split ar1 in 2 array row wise
print(spl)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [17]:
#splitting array according to index
#creating 1d array
d1 = np.array([0,1,2,3,4,5,6,7,8,9])
np.split(d1, [2,5,7]) #1st array will have 2nd index, 2nd array will have 5th index and 3rd will have 7th index

[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [19]:
#splitting array according to index
#creating 1d array
d1 = np.array([0,1,2,3,4,5,6,7,8,9])
np.split(d1, [2,5,9]) #1st array will have 2nd index, 2nd array will have 5th index and 3rd will have 9th index

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8]), array([9])]