# Array Slicing(:)

In [1]:
# Slicing in python means taking elements from one given index to another given index.

# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [2]:
import numpy as np

# Slicing 1d array

In [3]:
#Slice elements from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:5])
#Note: The result includes the start index, but excludes the end index.

[2 3 4 5]


In [4]:
#Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[4:])

[5 6 7 8 9]


In [5]:
#Slice elements from the beginning to index 8 (not included)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[:8])

[1 2 3 4 5 6 7 8]


# Negative Slicing

In [6]:
#Slice from the index 4 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[-4:-1])

[6 7 8]


In [7]:
#creating a matrix
mx = np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


# Basic conept of accessing and slicing

In [8]:
#silicing specific value in matrix [note indexing starts from 0]
mx[0,0] #0th row and 0th column

1

In [9]:
#finding the dimension of value
mx[0,0].ndim
#0 means no dimension and thus value is scalar

0

In [10]:
#slicing single row
mx[0] #(0th row) and (0 to 9 column as not mentioned)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#finding the dimension
mx[0].ndim
#1 means it's a 1d array

1

In [12]:
#slicing single column
mx[:, 0] #(0 to 9 row) and (0 to 9 column)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [13]:
#but above column is in 1d array and we want in 2d then
mx[:, 0:1] #(0 to 9 row) and (0 to 1 column means 1 column)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [14]:
#finding the dimension
mx[:, 0:1].ndim
#2 means it's a 2d array

2

# Slicing Specific 2d array

In [15]:
#slicing specific row and column
mx[1:4, 1:5] #(1 to 3 row) and (1 to 4 column) 
#Note: last number(4 and 5) is never included.

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35]])

In [16]:
#slicing specific row and column
mx[:, 2:4] #(all row) and (2 to 3 column)

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [17]:
#From the second element, slice elements from index 1 to index 4 (not included):
mx[1, 1:4]

array([12, 13, 14])

# Accessing full matrix

In [18]:
#accessig full matrix(method 1)
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [19]:
#accessig full matrix(method 2)
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
#accessig full matrix(method 3)
mx[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Size

In [21]:
mx.dtype #int matrix store in 64bit format

dtype('int64')

In [23]:
#1byte = 8 bit hence 64/8 = 8(matrix size), lets verify
mx.itemsize

8