In [1]:
#we imported numpy library as np
import numpy as np

In [2]:
#creating a unity matrix by typing whole matrix
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
#now using numpy we can do it easily using "ones"
mx1_1s = np.ones(5) #this will give the matrix of 1 with 5 colm
print(mx1_1s)

[1. 1. 1. 1. 1.]


In [4]:
#default matrix type is float, verified below
mx1_1s.dtype

dtype('float64')

In [5]:
#we have to given rows and colunm and create any size one's matrix
mx2_1s = np.ones((5,7))
print(mx2_1s)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
#we have changed the float type to integer
mx3_1s = np.ones((3,4), dtype = int)
print(mx3_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
#we have created a zero's matrix which is similar method to one's
mx4_0s = np.zeros((4,5))
print(mx4_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#we can also use the datatype as boolean, True is 1 & False is 0
mx5_0s = np.zeros((4,3), dtype = bool)
print(mx5_0s)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [9]:
#we have changed the float type to string
mx6_1s = np.ones((3,4), dtype = str)
print(mx6_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [10]:
#we can also use the datatype as string(for false or 0 we get empty string)
mx7_0s = np.zeros((4,3), dtype = str)
print(mx7_0s)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [11]:
#let verify mx7_0s output
em_str = "" #this is an empty string
print(bool(em_str)) #so empty str gives false i.e. 0

False


In [12]:
#we have to created empty matrix (NOTE: empty matrix in numpy is not empty but will give random values)
mx8_em = np.empty((3,3))
print(mx8_em)
#this matrix can be different on your pc as it's random!

[[ 1.14285714 -2.28571429  0.57142857]
 [-2.28571429  4.97142857 -1.54285714]
 [ 0.57142857 -1.54285714  0.88571429]]
