# Random Sampling

In [1]:
import numpy as np
# random imported which creates random values
import random

In [2]:
#creating random 1d array
ar1_1d = np.random.random(1) #'np.random' module is accessed | 'random' number is asked | '1' for single value
#note: it will give values between 0 and 1 only!
print(ar1_1d)

[0.14270175]


In [3]:
#creating random 2d array
ar2_2d = np.random.random((4,4)) #'np.random' module is accessed | 'random' random number is asked | 4 row and 4 column
#note: here brackets area doubled
print(ar2_2d)

[[0.50334878 0.80783165 0.3085549  0.92442082]
 [0.12441146 0.63767482 0.89349161 0.34573179]
 [0.96755756 0.764304   0.40886787 0.06459412]
 [0.44560009 0.33348825 0.66003955 0.72627648]]


# randint()

In [4]:
#integer value is wanted between 1 and 4
ar3_1d = np.random.randint(1,5) #'np.random' module is accessed 'randint' random integer number is asked
print(ar3_1d)

3


In [5]:
#2d random array
ar4_2d = np.random.randint(1,5, (4,4)) #'np.random' module is accessed 'randint' random integer number is asked in form of 2d array of 4 row and 4 column
print(ar4_2d)

[[2 2 3 1]
 [2 1 3 4]
 [3 1 2 4]
 [3 1 4 3]]


In [6]:
#3d random array
ar5_3d = np.random.randint(1,5, (2,3,3)) #'np.random' module is accessed 'randint' random integer number is asked in form of 3d array of 3 row and 3 column
print(ar5_3d)

[[[4 2 2]
  [3 3 4]
  [3 1 3]]

 [[2 4 2]
  [1 4 4]
  [2 4 3]]]


# Using specific random value again

In [7]:
#using one random value again
np.random.seed(12)
ar6_3d = np.random.randint(1,5, (2,3,3))
print(ar6_3d)

[[[4 4 3]
  [2 2 3]
  [4 4 1]]

 [[1 3 2]
  [1 2 2]
  [2 3 4]]]


In [8]:
#using one random value again
np.random.seed(12) #seed is used to use the specific random value again and again
ar7_3d = np.random.randint(1,5, (2,3,3))
print(ar7_3d)

[[[4 4 3]
  [2 2 3]
  [4 4 1]]

 [[1 3 2]
  [1 2 2]
  [2 3 4]]]


In [9]:
#here we can see that (ar6_3d = ar7_3d)
#above we have taken seed value 12, you must me wondering that how many random values can we take
#random values pattern can go upto
2**32 -1

4294967295

# rand()

In [10]:
#float values in 1d array
np.random.rand(3) 

array([0.13720932, 0.28382835, 0.60608318])

In [11]:
#float values in 2d array of 3x3
np.random.rand(3,3)

array([[0.94422514, 0.85273554, 0.00225923],
       [0.52122603, 0.55203763, 0.48537741],
       [0.76813415, 0.16071675, 0.76456045]])

# randn()

In [12]:
#negative and positive values in 2d array of 3x3
np.random.randn(3,3)

array([[-0.34947094, -0.70541676, -0.34018626],
       [ 2.02729871, -0.58108011,  0.87313484],
       [ 0.91056528,  1.04764561, -1.18963857]])

# Choosing

In [13]:
#choosing a random item from list
x = [1,2,3,4,5,6,7,8,9]
np.random.choice(x)

6

# Permutations

In [14]:
#for shuffling of list elements
np.random.permutation(x)

array([7, 3, 1, 2, 8, 9, 5, 4, 6])

In [15]:
#These were most commonly used but there are many more if you want visit:
# https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html